t = 'Curso em Vídeo Python'
print(t)
print(t[3])
print(t[3:10])
print(t[3:10:2])
print(t[:5])
print(t[7:])
print(t[3::3])
print('Tamanho: {}'.format(len(t)))
print('Os: {}'.format(t.count('o')))
print('Maiúscula: {}'.format(t.upper()))
print('Minúscula: {}'.format(t.lower()))
print('Captalizada: {}'.format(t.capitalize()))
print(t.replace('Python', 'Android'))
print('Tem Curso: {}'.format('Curso' in t))
